---
apiVersion: projectcalico.org/v3
kind: GlobalReport
metadata:
  name: daily-cluster-cis-benchmark-report
spec:
  reportType: cis-benchmark
  schedule: */10 * * * *
  cis:
    highThreshold: 100
    medThreshold: 50
    includeUnscoredTests: true
    numFailedTests: 5
